# Generated by Django 2.2.7 on 2020-02-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='unique_id',
            field=models.IntegerField(unique=True),
        ),
    ]
