# Generated by Django 2.2.6 on 2019-12-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='staff_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
