# Generated by Django 2.2.7 on 2019-12-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_trainee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('trainnee', models.ManyToManyField(to='course.Trainee')),
            ],
        ),
    ]
