# Generated by Django 2.2.7 on 2019-12-14 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_traineecourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traineecourse',
            old_name='trainnee',
            new_name='trainee',
        ),
        migrations.AlterField(
            model_name='employee',
            name='course_name',
            field=models.CharField(default='Empty Course', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_enrollment',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.PositiveIntegerField(default=243516113),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='staff_id',
            field=models.CharField(default=547812, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='station',
            field=models.CharField(default='Empty Station', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='summary',
            field=models.TextField(default='Empty Summary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(default='Empty Surname', max_length=150),
            preserve_default=False,
        ),
    ]
