# Generated by Django 2.2.7 on 2019-12-18 13:50

import course.models.employee
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20191214_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(default=None, upload_to=course.models.employee.upload_image_path),
            preserve_default=False,
        ),
    ]
