# Generated by Django 2.2.7 on 2019-12-19 16:55

import course.models.trainee
from django.db import migrations, models

from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20191218_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='avatar',
            field=models.ImageField(upload_to=course.models.trainee.upload_image_path),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='company',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainee',
            name='date_of_birth',
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainee',
            name='date_of_enrollment',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainee',
            name='mobile_number',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainee',
            name='other_name',
            field=models.CharField(default='trainee other name', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainee',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainee',
            name='status',
            field=models.CharField(choices=[('D', 'Done'), ('P', 'Pending')], default='D', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainee',
            name='summary',
            field=models.TextField(default='Summary of trainee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainee',
            name='surname',
            field=models.CharField(default='surname of trainee', max_length=150),
            preserve_default=False,
        ),
    ]
