# Generated by Django 2.2.7 on 2019-12-23 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20191219_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
