# Generated by Django 2.2.7 on 2020-01-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20200121_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
