# Generated by Django 2.2.7 on 2020-01-21 23:08

import course.models.trainee
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_trainee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=course.models.trainee.upload_image_path),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='other_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
