# Generated by Django 2.2.7 on 2020-01-22 08:57

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20200121_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='country',
            field=django_countries.fields.CountryField(default='GH', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
