# Generated by Django 2.2.7 on 2020-01-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
