# Generated by Django 2.2.7 on 2020-01-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20200126_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='traineecourse',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
